name: update-lockfiles

on:
  pull_request:
    branches:
      - "release-**"
    types:
      - closed

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  update-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: audit
      - name: Update lockfile(s) on closed PR
        uses: bazelbuild/continuous-integration/actions/update-lockfile@ca51d31b830088915518c6bb29fd268bd4f776f2
        with:
          release-branch: ${{ github.base_ref }}
          is-prod: True
          pr-number: ${{ github.event.number }}
